### ISSUE TITLE
x86 架构无法链接 与 无法正确安装总结

### ISSUE THREAD

**Issue by MooMooHorse** [wnlen/clash-for-linux#16]
同 [issue](https://github.com/wnlen/clash-for-linux/issues/5) #5 
感觉里面说的有点乱了，指出的问题比较零碎。感觉如果大家只是想科学上网的话，可能只需要一些能够做的尝试的可能性，**超级感谢这个自动安装clash的project**，但是中间还是碰到了一些问题。我是在刚刚装起来ubuntu 22.04上直接跑的，稍微总结下：
1. `curl` return value错误导致error checking 被kill了
```
#curl -o /dev/null -s -m 10 --connect-timeout 10 -w %{http_code} $URL | grep '[23][0-9][0-9]' &>/dev/null
curl -o /dev/null -L -k -sS --retry 5 -m 10 --connect-timeout 10 -w "%{http_code}" $URL | grep -E '^[23][0-9]{2}$' &>/dev/null
ReturnStatus=$?
if_success $Text1 $Text2 $ReturnStatus
```
这里的return value 我是1，然后中间报错是curl 到missing / bad url。但我又确认订阅链接是好的，也改了script看了下`$URL`也没问题。

### 解决方案
首先先检查下subscription link是不是对的。subscription link是机场提供的订阅链接，但是对于clash / v2ray / ... 等客户端需要转换下链接，这个链接是需要一个后端支持的，但很多转换的平台后端都挂啦，所以可能要注意检查下转换后的链接是不是ok滴。如果想检查自己的subscription link 有没有用，最简单可以直接在浏览器里粘贴下订阅链接。正常的clash订阅链接应该是能看到以下这样的

```
port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
dns:
  enabled: true
  nameserver:
    - .....
  fallback:
    - ....
proxies:
  - {name: 距离下次重置剩余：17 天, server: ....}
  - {name: ...}
 ....
  - {name: 🇺🇸 0.7x 🇺🇸 美国17, server: ...., port: ...., client-fingerprint: chrome, type: vmess, uuid: ...}
  ....
```
然而我虽然链接是对的，但是还是curl 的return value错了，我也不想研究，直接注释掉这行直接把这行注释掉 `if_success $Text1 $Text2 $ReturnStatus`，之后`config`的yaml文件还是可以正常下载的。

2. X86 无法链接，无法上网 #5 

这个问题状况跟 #5 一样，但里面的讨论似乎没有直接给解决方案，其实很简单啦，用GUI把 proxy 开起来，**注意这张图我是随便偷的，里面填的是`127.0.0.1` 和 `7890`。他们和 `$http_proxy` `$https_proxy` 的值应该是一样的**，我没填FTP 和 SOCKS。
![image](https://github.com/wnlen/clash-for-linux/assets/81849674/a89739da-fbba-4dcb-9c5b-f6daa41f28c4)

3. 服务器启动成功，GUI卡在一个界面（无法访问UI界面） #8 

这个跟 #8 一样, 解决也很简单啦，重新跑下 `start.sh` 就行，感觉是哪里被corrupt了，不懂也不想研究hhhh，但我这样就解决咧。
